sudo: required

language: go
go:
  - "1.10.x"

before_install:
  - go get github.com/mattn/goveralls
  - docker-compose -f ci/docker-compose.yml up -d

script: "go test -v ./... -coverprofile=coverage.out -covermode=count"

after_success:
  - "$GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN"

services:
  - docker
