// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dependency.proto

/*
	Package thunderpb is a generated protocol buffer package.

	It is generated from these files:
		dependency.proto

	It has these top-level messages:
		Field
		SQLFilter
		ExpirationTime
*/
package thunderpb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/gogo/protobuf/types"

import time "time"

import binary "encoding/binary"
import types "github.com/gogo/protobuf/types"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type FieldKind int32

const (
	FieldKind_Unknown FieldKind = 0
	FieldKind_Null    FieldKind = 1
	FieldKind_Bool    FieldKind = 2
	FieldKind_Int     FieldKind = 3
	FieldKind_Uint    FieldKind = 4
	FieldKind_String  FieldKind = 5
	FieldKind_Bytes   FieldKind = 6
	FieldKind_Float64 FieldKind = 7
	FieldKind_Time    FieldKind = 8
)

var FieldKind_name = map[int32]string{
	0: "Unknown",
	1: "Null",
	2: "Bool",
	3: "Int",
	4: "Uint",
	5: "String",
	6: "Bytes",
	7: "Float64",
	8: "Time",
}
var FieldKind_value = map[string]int32{
	"Unknown": 0,
	"Null":    1,
	"Bool":    2,
	"Int":     3,
	"Uint":    4,
	"String":  5,
	"Bytes":   6,
	"Float64": 7,
	"Time":    8,
}

func (x FieldKind) String() string {
	return proto.EnumName(FieldKind_name, int32(x))
}
func (FieldKind) EnumDescriptor() ([]byte, []int) { return fileDescriptorDependency, []int{0} }

type Field struct {
	Kind    FieldKind `protobuf:"varint,1,opt,name=kind,proto3,enum=thunderpb.FieldKind" json:"kind,omitempty"`
	Bool    bool      `protobuf:"varint,2,opt,name=bool,proto3" json:"bool,omitempty"`
	Int     int64     `protobuf:"zigzag64,3,opt,name=int,proto3" json:"int,omitempty"`
	Uint    uint64    `protobuf:"varint,4,opt,name=uint,proto3" json:"uint,omitempty"`
	String_ string    `protobuf:"bytes,5,opt,name=string,proto3" json:"string,omitempty"`
	Bytes   []byte    `protobuf:"bytes,6,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Float64 float64   `protobuf:"fixed64,7,opt,name=float64,proto3" json:"float64,omitempty"`
	Time    time.Time `protobuf:"bytes,8,opt,name=time,stdtime" json:"time"`
}

func (m *Field) Reset()                    { *m = Field{} }
func (m *Field) String() string            { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()               {}
func (*Field) Descriptor() ([]byte, []int) { return fileDescriptorDependency, []int{0} }

func (m *Field) GetKind() FieldKind {
	if m != nil {
		return m.Kind
	}
	return FieldKind_Unknown
}

func (m *Field) GetBool() bool {
	if m != nil {
		return m.Bool
	}
	return false
}

func (m *Field) GetInt() int64 {
	if m != nil {
		return m.Int
	}
	return 0
}

func (m *Field) GetUint() uint64 {
	if m != nil {
		return m.Uint
	}
	return 0
}

func (m *Field) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

func (m *Field) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *Field) GetFloat64() float64 {
	if m != nil {
		return m.Float64
	}
	return 0
}

func (m *Field) GetTime() time.Time {
	if m != nil {
		return m.Time
	}
	return time.Time{}
}

type SQLFilter struct {
	Table string `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	// Map of column name to field value.
	Fields map[string]*Field `protobuf:"bytes,2,rep,name=fields" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *SQLFilter) Reset()                    { *m = SQLFilter{} }
func (m *SQLFilter) String() string            { return proto.CompactTextString(m) }
func (*SQLFilter) ProtoMessage()               {}
func (*SQLFilter) Descriptor() ([]byte, []int) { return fileDescriptorDependency, []int{1} }

func (m *SQLFilter) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *SQLFilter) GetFields() map[string]*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ExpirationTime struct {
	Time time.Time `protobuf:"bytes,1,opt,name=time,stdtime" json:"time"`
}

func (m *ExpirationTime) Reset()                    { *m = ExpirationTime{} }
func (m *ExpirationTime) String() string            { return proto.CompactTextString(m) }
func (*ExpirationTime) ProtoMessage()               {}
func (*ExpirationTime) Descriptor() ([]byte, []int) { return fileDescriptorDependency, []int{2} }

func (m *ExpirationTime) GetTime() time.Time {
	if m != nil {
		return m.Time
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*Field)(nil), "thunderpb.Field")
	proto.RegisterType((*SQLFilter)(nil), "thunderpb.SQLFilter")
	proto.RegisterType((*ExpirationTime)(nil), "thunderpb.ExpirationTime")
	proto.RegisterEnum("thunderpb.FieldKind", FieldKind_name, FieldKind_value)
}
func (m *Field) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Field) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Kind != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintDependency(dAtA, i, uint64(m.Kind))
	}
	if m.Bool {
		dAtA[i] = 0x10
		i++
		if m.Bool {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Int != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintDependency(dAtA, i, uint64((uint64(m.Int)<<1)^uint64((m.Int>>63))))
	}
	if m.Uint != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintDependency(dAtA, i, uint64(m.Uint))
	}
	if len(m.String_) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintDependency(dAtA, i, uint64(len(m.String_)))
		i += copy(dAtA[i:], m.String_)
	}
	if len(m.Bytes) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintDependency(dAtA, i, uint64(len(m.Bytes)))
		i += copy(dAtA[i:], m.Bytes)
	}
	if m.Float64 != 0 {
		dAtA[i] = 0x39
		i++
		binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Float64))))
		i += 8
	}
	dAtA[i] = 0x42
	i++
	i = encodeVarintDependency(dAtA, i, uint64(types.SizeOfStdTime(m.Time)))
	n1, err := types.StdTimeMarshalTo(m.Time, dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	return i, nil
}

func (m *SQLFilter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SQLFilter) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Table) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintDependency(dAtA, i, uint64(len(m.Table)))
		i += copy(dAtA[i:], m.Table)
	}
	if len(m.Fields) > 0 {
		for k, _ := range m.Fields {
			dAtA[i] = 0x12
			i++
			v := m.Fields[k]
			msgSize := 0
			if v != nil {
				msgSize = v.Size()
				msgSize += 1 + sovDependency(uint64(msgSize))
			}
			mapSize := 1 + len(k) + sovDependency(uint64(len(k))) + msgSize
			i = encodeVarintDependency(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintDependency(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			if v != nil {
				dAtA[i] = 0x12
				i++
				i = encodeVarintDependency(dAtA, i, uint64(v.Size()))
				n2, err := v.MarshalTo(dAtA[i:])
				if err != nil {
					return 0, err
				}
				i += n2
			}
		}
	}
	return i, nil
}

func (m *ExpirationTime) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExpirationTime) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintDependency(dAtA, i, uint64(types.SizeOfStdTime(m.Time)))
	n3, err := types.StdTimeMarshalTo(m.Time, dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n3
	return i, nil
}

func encodeVarintDependency(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Field) Size() (n int) {
	var l int
	_ = l
	if m.Kind != 0 {
		n += 1 + sovDependency(uint64(m.Kind))
	}
	if m.Bool {
		n += 2
	}
	if m.Int != 0 {
		n += 1 + sozDependency(uint64(m.Int))
	}
	if m.Uint != 0 {
		n += 1 + sovDependency(uint64(m.Uint))
	}
	l = len(m.String_)
	if l > 0 {
		n += 1 + l + sovDependency(uint64(l))
	}
	l = len(m.Bytes)
	if l > 0 {
		n += 1 + l + sovDependency(uint64(l))
	}
	if m.Float64 != 0 {
		n += 9
	}
	l = types.SizeOfStdTime(m.Time)
	n += 1 + l + sovDependency(uint64(l))
	return n
}

func (m *SQLFilter) Size() (n int) {
	var l int
	_ = l
	l = len(m.Table)
	if l > 0 {
		n += 1 + l + sovDependency(uint64(l))
	}
	if len(m.Fields) > 0 {
		for k, v := range m.Fields {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovDependency(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovDependency(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovDependency(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *ExpirationTime) Size() (n int) {
	var l int
	_ = l
	l = types.SizeOfStdTime(m.Time)
	n += 1 + l + sovDependency(uint64(l))
	return n
}

func sovDependency(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozDependency(x uint64) (n int) {
	return sovDependency(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Field) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDependency
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Field: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Field: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			m.Kind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDependency
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Kind |= (FieldKind(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bool", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDependency
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Bool = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Int", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDependency
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = (v >> 1) ^ uint64((int64(v&1)<<63)>>63)
			m.Int = int64(v)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uint", wireType)
			}
			m.Uint = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDependency
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Uint |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field String_", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDependency
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDependency
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.String_ = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bytes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDependency
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDependency
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bytes = append(m.Bytes[:0], dAtA[iNdEx:postIndex]...)
			if m.Bytes == nil {
				m.Bytes = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Float64", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Float64 = float64(math.Float64frombits(v))
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDependency
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDependency
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := types.StdTimeUnmarshal(&m.Time, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDependency(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDependency
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SQLFilter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDependency
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SQLFilter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SQLFilter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Table", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDependency
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDependency
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Table = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fields", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDependency
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDependency
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Fields == nil {
				m.Fields = make(map[string]*Field)
			}
			var mapkey string
			var mapvalue *Field
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowDependency
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowDependency
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthDependency
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowDependency
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= (int(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthDependency
					}
					postmsgIndex := iNdEx + mapmsglen
					if mapmsglen < 0 {
						return ErrInvalidLengthDependency
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &Field{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipDependency(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthDependency
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Fields[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDependency(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDependency
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExpirationTime) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDependency
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExpirationTime: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExpirationTime: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDependency
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDependency
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := types.StdTimeUnmarshal(&m.Time, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDependency(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDependency
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDependency(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDependency
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDependency
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDependency
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthDependency
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowDependency
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipDependency(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthDependency = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDependency   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("dependency.proto", fileDescriptorDependency) }

var fileDescriptorDependency = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x6e, 0xd3, 0x30,
	0x1c, 0xc6, 0xe7, 0x36, 0x49, 0x9b, 0x7f, 0xd1, 0x64, 0x59, 0x13, 0x8a, 0x7a, 0x68, 0xa3, 0x1e,
	0x26, 0x0b, 0x89, 0x54, 0x2a, 0x13, 0xaa, 0x38, 0x56, 0x5a, 0x25, 0x18, 0x42, 0xc2, 0x63, 0x17,
	0x6e, 0xc9, 0xe2, 0xa6, 0x56, 0x5d, 0xbb, 0x24, 0x0e, 0xd0, 0xb7, 0xe0, 0x31, 0x78, 0x94, 0x1d,
	0x79, 0x02, 0x40, 0xbd, 0xf3, 0x0e, 0xc8, 0x4e, 0x5b, 0x2a, 0x6e, 0xbb, 0x7d, 0x9f, 0xfd, 0xd9,
	0xce, 0xef, 0xfb, 0x07, 0x70, 0xce, 0x37, 0x5c, 0xe5, 0x5c, 0xdd, 0x6f, 0x93, 0x4d, 0xa9, 0x8d,
	0x26, 0xa1, 0x59, 0xd6, 0x2a, 0xe7, 0xe5, 0x26, 0xeb, 0x3f, 0x2f, 0x84, 0x59, 0xd6, 0x59, 0x72,
	0xaf, 0xd7, 0xe3, 0x42, 0x17, 0x7a, 0xec, 0x12, 0x59, 0xbd, 0x70, 0xce, 0x19, 0xa7, 0x9a, 0x93,
	0xfd, 0x61, 0xa1, 0x75, 0x21, 0xf9, 0xbf, 0x94, 0x11, 0x6b, 0x5e, 0x99, 0x74, 0xbd, 0x69, 0x02,
	0xa3, 0x3f, 0x08, 0xfc, 0xb9, 0xe0, 0x32, 0x27, 0x14, 0xbc, 0x95, 0x50, 0x79, 0x84, 0x62, 0x44,
	0xcf, 0x27, 0x17, 0xc9, 0xf1, 0xcd, 0xc4, 0xed, 0xdf, 0x08, 0x95, 0x33, 0x97, 0x20, 0x04, 0xbc,
	0x4c, 0x6b, 0x19, 0xb5, 0x62, 0x44, 0xbb, 0xcc, 0x69, 0x82, 0xa1, 0x2d, 0x94, 0x89, 0xda, 0x31,
	0xa2, 0x84, 0x59, 0x69, 0x53, 0xb5, 0x5d, 0xf2, 0x62, 0x44, 0x3d, 0xe6, 0x34, 0x79, 0x0a, 0x41,
	0x65, 0x4a, 0xa1, 0x8a, 0xc8, 0x8f, 0x11, 0x0d, 0xd9, 0xde, 0x91, 0x0b, 0xf0, 0xb3, 0xad, 0xe1,
	0x55, 0x14, 0xc4, 0x88, 0x3e, 0x61, 0x8d, 0x21, 0x11, 0x74, 0x16, 0x52, 0xa7, 0xe6, 0xe5, 0x55,
	0xd4, 0x89, 0x11, 0x45, 0xec, 0x60, 0xc9, 0x14, 0x3c, 0x0b, 0x12, 0x75, 0x63, 0x44, 0x7b, 0x93,
	0x7e, 0xd2, 0x50, 0x26, 0x07, 0xca, 0xe4, 0xc3, 0x81, 0x72, 0xd6, 0x7d, 0xf8, 0x39, 0x3c, 0xfb,
	0xf6, 0x6b, 0x88, 0x98, 0x3b, 0x31, 0xfa, 0x8e, 0x20, 0xbc, 0x7d, 0xff, 0x76, 0x2e, 0xa4, 0xe1,
	0xa5, 0x7d, 0xd7, 0xa4, 0x99, 0xe4, 0x0e, 0x3a, 0x64, 0x8d, 0x21, 0x53, 0x08, 0x16, 0x16, 0xb9,
	0x8a, 0x5a, 0x71, 0x9b, 0xf6, 0x26, 0xf1, 0x49, 0x17, 0xc7, 0xb3, 0x4d, 0x2b, 0xd5, 0xb5, 0x32,
	0xe5, 0x96, 0xed, 0xf3, 0xfd, 0x1b, 0xe8, 0x9d, 0x2c, 0xdb, 0x52, 0x56, 0x7c, 0xbb, 0xbf, 0xdc,
	0x4a, 0x72, 0x09, 0xfe, 0xe7, 0x54, 0xd6, 0xdc, 0x75, 0xd7, 0x9b, 0xe0, 0xff, 0x5b, 0x66, 0xcd,
	0xf6, 0xab, 0xd6, 0x14, 0x8d, 0xde, 0xc0, 0xf9, 0xf5, 0xd7, 0x8d, 0x28, 0x53, 0x23, 0xb4, 0xb2,
	0x44, 0x47, 0x6c, 0xf4, 0x58, 0xec, 0x67, 0x6b, 0x08, 0x8f, 0x53, 0x24, 0x3d, 0xe8, 0xdc, 0xa9,
	0x95, 0xd2, 0x5f, 0x14, 0x3e, 0x23, 0x5d, 0xf0, 0xde, 0xd5, 0x52, 0x62, 0x64, 0xd5, 0x4c, 0x6b,
	0x89, 0x5b, 0xa4, 0x03, 0xed, 0xd7, 0xca, 0xe0, 0xb6, 0x5d, 0xba, 0x13, 0xca, 0x60, 0x8f, 0x00,
	0x04, 0xb7, 0x6e, 0x56, 0xd8, 0x27, 0x21, 0xf8, 0x33, 0x3b, 0x20, 0x1c, 0xd8, 0xab, 0xe6, 0xcd,
	0x4c, 0x70, 0xc7, 0xa6, 0xed, 0x17, 0xe0, 0xee, 0xec, 0xea, 0x61, 0x37, 0x40, 0x3f, 0x76, 0x03,
	0xf4, 0x7b, 0x37, 0x40, 0x1f, 0x2f, 0x4f, 0xfe, 0xd9, 0x2a, 0x5d, 0x57, 0x69, 0x99, 0x2e, 0x3f,
	0x8d, 0xf7, 0xe4, 0xe3, 0x63, 0x03, 0x59, 0xe0, 0x40, 0x5e, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0xaa, 0x1a, 0xf8, 0x82, 0x01, 0x03, 0x00, 0x00,
}
