version: '2'

services:
  mysql:
    image: mysql:5.6
    volumes:
      - ./binlog.cnf:/etc/mysql/conf.d/binlog.cnf
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "dev"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

